
import 'package:project_uas/models/product_model.dart';

List<ProductModel> pro = [
  ProductModel(name: "HP Iphone 13 pro", price: "Rp 8.000.000", ratings: 3.4, favorite: false, img: "aset/awa/ip13.jpeg", desk: 'APPLE IPHONE 11 PRO MAX 256GB GARANSI RESMI IBOX - Gold',id: 0, chart: false),
  ProductModel(name: "Laptop Asus ROG Strix G16 G614PM", price: "Rp 28.300.000", ratings: 4.2, favorite: false, img: "aset/awa/rog.jpg", desk: 'Asus ROG Strix G16 G614PM-R9N56C6G-HM /AMD Ryzen 9-8940HX/16GB/1TB SSD/NVIDIA GeForce RTX 5060 8GB/16″ WQXGA/Win 11 Home+OHM+M365/Eclipse Gray/2Y',id: 1, chart: false),
  ProductModel(name: "Sepatu Adidas Adi zero 2.0", price: "Rp 8.000.000", ratings: 3.0, favorite: false, img: "aset/awa/adizero1.jpg", desk: 'SEPATU KOMPETISI LARI BERKONSTRUKSI TINGGI YANG DILENGKAPI FITUR YANG MENUNJANG PERFORMA.',id: 2, chart: false),
  ProductModel(name: "Sepatu 910 KANZAKI 1.0", price: "Rp 12.000.000", ratings: 2.4, favorite: false, img: "aset/awa/kanzaki.jpg", desk: 'Sepatu 910 Kanzaki 1.0 Original Sepatu Nineten Training Sport Running Olahraga Lari Original',id: 3, chart: false),
  ProductModel(name: "Sepatu Hoka Clifton 10", price: "Rp 9.000.000", ratings: 3.7, favorite: false, img: "aset/awa/clifton.jpg", desk: 'Hoka Clifton 10 dalam warna beige merupakan sepatu lari ringan yang dirancang untuk menunjang aktivitas harian dengan kenyamanan maksimal',id: 4, chart: false),
  ProductModel(name: "Baju SAMGONG 30", price: "Rp 200.000", ratings: 5.0, favorite: false, img: "aset/awa/samgong.jpg", desk: 'pakaian kasual santai seperti kaos oblong atau setelan celana pendek dengan bahan yang nyaman (biasanya babyterry atau katun), yang sering digunakan sebagai pakaian kasual sehari-hari, santai, atau distro.',id: 5, chart: false),
  ProductModel(name: "Baju Batik motif Megamendung", price: "Rp 150.000", ratings: 5.0, favorite: false, img: "aset/awa/mega.jpg", desk: 'Batik Megamendung merupakan karya seni batik yang identik dan bahkan menjadi ikon batik daerah Cirebon[1] dan daerah Indonesia lainnya.',id: 6, chart: false),
  ProductModel(name: "Makanan Ayam Bakar Pak Slamet", price: "Rp 24.000", ratings: 4.2, favorite: false, img: "aset/awa/ayambakar.jpg", desk: 'daging ayam kampung empuk yang dibakar dengan bumbu kecap pekat, meresap hingga ke serat, serta disajikan dengan sambal pedas',id: 7, chart: false),
  ProductModel(name: "Minuman Milk tea mbak roja", price: "Rp 10.000", ratings: 3.1, favorite: false, img: "aset/awa/milkt.jpg", desk: 'minuman populer yang terbuat dari campuran teh dan susu, yang umumnya disajikan dengan pemanis seperti gula, madu, atau sirup',id: 8, chart: false),
  ProductModel(name: "Laptop ASUS Vivobook 16X", price: "Rp 10.100.000", ratings: 1.1, favorite: false, img: "aset/awa/vivobook.jpg", desk: 'laptop kreator bertenaga dengan harga menengah, ideal untuk produktivitas, multitasking, dan gaming kasual.', id: 9, chart: false),
];